name: testing
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install xvfb
        run: sudo apt-get install -y xvfb
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install -r requirements.txt
      - name: Run tests with xvfb and collect coverage
        run: |
          xvfb-run coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml  # Generate XML report for Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mbdgoes/Blackjack-GUI

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml  # Generate XML report for Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mbdgoes/Blackjack-GUI

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml  # Generate XML report for Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mbdgoes/Blackjack-GUI
